# Generated by Django 4.2.20 on 2025-04-03 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("psychotest", "0002_category_option_category_scores_result_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="권장 크기: 110x150",
                null=True,
                upload_to="test_images/",
                verbose_name="테스트 이미지",
            ),
        ),
        migrations.AddField(
            model_name="test",
            name="view_count",
            field=models.PositiveIntegerField(default=0, verbose_name="조회수"),
        ),
    ]
