# Generated by Django 4.2.20 on 2025-04-09 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("psychotest", "0004_result_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="intro_image",
            field=models.ImageField(
                blank=True,
                help_text="권장 크기: 500x500",
                null=True,
                upload_to="test_intro_images/",
                verbose_name="인트로 이미지",
            ),
        ),
    ]
