# Generated by Django 4.2.20 on 2025-04-18 07:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("psychotest", "0005_test_intro_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="SharedTestResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "score",
                    models.IntegerField(blank=True, null=True, verbose_name="점수"),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="카테고리"
                    ),
                ),
                (
                    "category_scores",
                    models.JSONField(
                        blank=True, null=True, verbose_name="카테고리별 점수"
                    ),
                ),
                (
                    "calculation_method",
                    models.CharField(
                        choices=[
                            ("sum", "점수 합산"),
                            ("category", "카테고리 점수"),
                            ("pattern", "패턴 매칭"),
                        ],
                        default="sum",
                        max_length=20,
                        verbose_name="계산 방식",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shared_instances",
                        to="psychotest.result",
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shared_results",
                        to="psychotest.test",
                    ),
                ),
            ],
            options={
                "verbose_name": "공유된 테스트 결과",
                "verbose_name_plural": "공유된 테스트 결과들",
                "ordering": ["-created_at"],
            },
        ),
    ]
