# Generated by Django 4.2.20 on 2025-04-18 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("psychotest", "0006_sharedtestresult"),
    ]

    operations = [
        migrations.AddField(
            model_name="sharedtestresult",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="권장 크기: 500x600px",
                null=True,
                upload_to="question_images/",
                verbose_name="질문 이미지",
            ),
        ),
    ]
