# Generated by Django 4.2.11 on 2025-11-11 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="카테고리명"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=100, unique=True, verbose_name="슬러그"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="이모지 또는 아이콘 클래스명",
                        max_length=50,
                        verbose_name="아이콘",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성화")),
                ("order", models.IntegerField(default=0, verbose_name="정렬 순서")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
            ],
            options={
                "verbose_name": "카테고리",
                "verbose_name_plural": "카테고리 목록",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="SubCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="하위 카테고리명"),
                ),
                ("slug", models.SlugField(max_length=100, verbose_name="슬러그")),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                ("is_active", models.BooleanField(default=True, verbose_name="활성화")),
                ("order", models.IntegerField(default=0, verbose_name="정렬 순서")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="core.category",
                        verbose_name="상위 카테고리",
                    ),
                ),
            ],
            options={
                "verbose_name": "하위 카테고리",
                "verbose_name_plural": "하위 카테고리 목록",
                "ordering": ["order", "name"],
                "unique_together": {("category", "slug")},
            },
        ),
    ]
