# Generated by Django 4.2.11 on 2025-11-12 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="icon",
            field=models.ImageField(
                blank=True,
                help_text="카테고리 아이콘 이미지 (권장 크기: 200x200px)",
                null=True,
                upload_to="category_icons/",
                verbose_name="아이콘 이미지",
            ),
        ),
    ]
