# Generated by Django 4.2.11 on 2025-11-21 10:25

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_category_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="subcategory",
            name="icon_image",
            field=models.ImageField(
                blank=True,
                help_text="정사각형 이미지만 업로드 가능 (예: 512x512)",
                null=True,
                upload_to="subcategory_icons/",
                validators=[core.models.validate_square_image],
                verbose_name="아이콘 이미지",
            ),
        ),
    ]
