# Generated by Django 4.2.11 on 2025-12-01 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TossApp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "app_id",
                    models.CharField(
                        help_text="영문 소문자와 언더스코어만 사용 (예: game_honey, paljalog)",
                        max_length=50,
                        unique=True,
                        verbose_name="앱 ID",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="사용자에게 표시되는 앱 이름 (예: 게임 하니, 팔자로그)",
                        max_length=100,
                        verbose_name="앱 이름",
                    ),
                ),
                (
                    "toss_client_id",
                    models.CharField(
                        blank=True,
                        help_text="Toss 개발자센터에서 발급받은 Client ID",
                        max_length=255,
                        verbose_name="Toss Client ID",
                    ),
                ),
                (
                    "toss_decrypt_key",
                    models.CharField(
                        blank=True,
                        help_text="Base64 인코딩된 AES-256-GCM 복호화 키",
                        max_length=500,
                        verbose_name="Toss 복호화 키",
                    ),
                ),
                (
                    "toss_decrypt_aad",
                    models.CharField(
                        default="TOSS",
                        help_text="Additional Authenticated Data (기본값: TOSS)",
                        max_length=50,
                        verbose_name="Toss AAD",
                    ),
                ),
                (
                    "cert_path",
                    models.CharField(
                        blank=True,
                        help_text="mTLS 인증서 파일 경로 (예: mtls/game_honey/cert.pem)",
                        max_length=500,
                        verbose_name="인증서 경로",
                    ),
                ),
                (
                    "key_path",
                    models.CharField(
                        blank=True,
                        help_text="mTLS 키 파일 경로 (예: mtls/game_honey/key.pem)",
                        max_length=500,
                        verbose_name="키 경로",
                    ),
                ),
                (
                    "disconnect_callback_username",
                    models.CharField(
                        blank=True,
                        help_text="Toss 연결 끊기 콜백 Basic Auth Username",
                        max_length=100,
                        verbose_name="콜백 Username",
                    ),
                ),
                (
                    "disconnect_callback_password",
                    models.CharField(
                        blank=True,
                        help_text="Toss 연결 끊기 콜백 Basic Auth Password",
                        max_length=255,
                        verbose_name="콜백 Password",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="비활성화하면 해당 앱으로 로그인할 수 없습니다",
                        verbose_name="활성화",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
            ],
            options={
                "verbose_name": "Toss 앱",
                "verbose_name_plural": "Toss 앱 목록",
                "ordering": ["display_name"],
            },
        ),
        migrations.CreateModel(
            name="AppUserToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "toss_access_token",
                    models.TextField(blank=True, verbose_name="Toss Access Token"),
                ),
                (
                    "toss_refresh_token",
                    models.TextField(blank=True, verbose_name="Toss Refresh Token"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_tokens",
                        to="common.tossapp",
                        verbose_name="앱",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="app_tokens",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "앱별 사용자 토큰",
                "verbose_name_plural": "앱별 사용자 토큰 목록",
                "ordering": ["-updated_at"],
                "unique_together": {("user", "app")},
            },
        ),
    ]
