# Generated by Django 4.2.11 on 2025-11-19 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="toss_access_token",
            field=models.TextField(blank=True, verbose_name="토스 액세스 토큰"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="toss_refresh_token",
            field=models.TextField(blank=True, verbose_name="토스 리프레시 토큰"),
        ),
    ]
