# Generated by Django 4.2.11 on 2025-11-19 04:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0002_alter_userprofile_toss_access_token_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PremiumSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subscription_type",
                    models.CharField(
                        choices=[
                            ("free_ad", "광고 시청 무료 (7일)"),
                            ("premium", "프리미엄 구독 (30일)"),
                        ],
                        max_length=20,
                        verbose_name="구독 유형",
                    ),
                ),
                ("expires_at", models.DateTimeField(verbose_name="만료일시")),
                (
                    "order_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="주문 ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="premium_subscription",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "프리미엄 구독",
                "verbose_name_plural": "프리미엄 구독 목록",
                "ordering": ["-created_at"],
            },
        ),
    ]
