# Generated by Django 4.2.11 on 2025-11-21 08:50

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_premiumsubscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="icon_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="game_icons/",
                validators=[api.models.validate_square_image],
                verbose_name="게임 아이콘 이미지",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="icon_url",
            field=models.URLField(blank=True, verbose_name="아이콘 URL (레거시)"),
        ),
        migrations.AlterField(
            model_name="premiumsubscription",
            name="subscription_type",
            field=models.CharField(
                choices=[
                    ("free_ad", "광고 시청 무료 (7일)"),
                    ("premium", "프리미엄 구독 (180일)"),
                ],
                max_length=20,
                verbose_name="구독 유형",
            ),
        ),
    ]
