# Generated by Django 4.2.11 on 2025-12-06 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0004_game_icon_image_alter_game_icon_url_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CarrotTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("ad_reward", "광고 시청 보상"),
                            ("recipe_recommend", "요리 추천"),
                            ("recipe_another", "다른 요리 추천"),
                            ("purchase_100", "당근 100개 구매"),
                            ("purchase_1000", "당근 1000개 구매"),
                            ("purchase_5000", "당근 5000개 구매"),
                            ("purchase_10000", "당근 10000개 구매"),
                            ("admin_grant", "관리자 지급"),
                            ("admin_deduct", "관리자 차감"),
                        ],
                        max_length=30,
                        verbose_name="거래 유형",
                    ),
                ),
                ("amount", models.IntegerField(verbose_name="변동량")),
                ("balance_after", models.IntegerField(verbose_name="거래 후 잔액")),
                (
                    "order_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="주문 ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="거래일시"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carrot_transactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "당근 거래 내역",
                "verbose_name_plural": "당근 거래 내역 목록",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CarrotBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("balance", models.IntegerField(default=0, verbose_name="당근 잔액")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carrot_balance",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "당근 잔액",
                "verbose_name_plural": "당근 잔액 목록",
            },
        ),
    ]
