# Generated by Django 4.2.11 on 2025-12-07 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0005_add_carrot_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carrottransaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("welcome_bonus", "첫 로그인 보너스"),
                    ("ad_reward", "광고 시청 보상"),
                    ("recipe_recommend", "요리 추천"),
                    ("recipe_another", "다른 요리 추천"),
                    ("purchase_100", "당근 100개 구매"),
                    ("purchase_1000", "당근 1000개 구매"),
                    ("purchase_5000", "당근 5000개 구매"),
                    ("purchase_10000", "당근 10000개 구매"),
                    ("admin_grant", "관리자 지급"),
                    ("admin_deduct", "관리자 차감"),
                ],
                max_length=30,
                verbose_name="거래 유형",
            ),
        ),
        migrations.CreateModel(
            name="SavedRecipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recipe_id",
                    models.CharField(max_length=100, verbose_name="레시피 ID"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="요리명")),
                ("description", models.CharField(max_length=200, verbose_name="설명")),
                ("difficulty", models.CharField(max_length=20, verbose_name="난이도")),
                ("time", models.IntegerField(verbose_name="조리시간(분)")),
                ("servings", models.CharField(max_length=20, verbose_name="인분")),
                (
                    "ingredients",
                    models.JSONField(default=list, verbose_name="재료 목록"),
                ),
                ("steps", models.JSONField(default=list, verbose_name="조리 단계")),
                ("tips", models.JSONField(default=list, verbose_name="요리 팁")),
                (
                    "used_ingredients",
                    models.JSONField(default=list, verbose_name="사용 재료"),
                ),
                (
                    "additional_ingredients",
                    models.JSONField(default=list, verbose_name="추가 재료"),
                ),
                (
                    "saved_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="저장일시"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_recipes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "저장된 레시피",
                "verbose_name_plural": "저장된 레시피 목록",
                "ordering": ["-saved_at"],
                "unique_together": {("user", "recipe_id")},
            },
        ),
    ]
