# Generated by Django 4.2.20 on 2025-04-25 18:38

from django.db import migrations, models
import django.db.models.deletion
import facetest.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FaceModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="모델명")),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                (
                    "model_file",
                    models.FileField(
                        upload_to=facetest.models.model_file_upload_path,
                        verbose_name="모델 파일",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성화")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
            ],
            options={
                "verbose_name": "얼굴상 모델",
                "verbose_name_plural": "얼굴상 모델",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FaceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="유형명")),
                (
                    "code",
                    models.CharField(
                        help_text="모델이 예측에 사용하는 클래스명",
                        max_length=50,
                        verbose_name="코드",
                    ),
                ),
                ("description", models.TextField(verbose_name="설명")),
                (
                    "characteristics",
                    models.TextField(
                        blank=True,
                        help_text="특징을 한 줄에 하나씩 작성하세요",
                        verbose_name="특징",
                    ),
                ),
                (
                    "examples",
                    models.TextField(
                        blank=True,
                        help_text="예시를 한 줄에 하나씩 작성하세요",
                        verbose_name="예시",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="face_types/", verbose_name="대표 이미지"
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="face_types",
                        to="facetest.facemodel",
                        verbose_name="모델",
                    ),
                ),
            ],
            options={
                "verbose_name": "얼굴 유형",
                "verbose_name_plural": "얼굴 유형",
                "unique_together": {("code", "model")},
            },
        ),
        migrations.CreateModel(
            name="FaceTestResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=facetest.models.face_image_upload_path,
                        verbose_name="얼굴 이미지",
                    ),
                ),
                ("probability", models.FloatField(verbose_name="확률")),
                (
                    "all_results",
                    models.JSONField(default=dict, verbose_name="모든 결과"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "face_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="facetest.facetype",
                        verbose_name="얼굴 유형",
                    ),
                ),
            ],
            options={
                "verbose_name": "얼굴 테스트 결과",
                "verbose_name_plural": "얼굴 테스트 결과",
                "ordering": ["-created_at"],
            },
        ),
    ]
