# Generated by Django 4.2.20 on 2025-04-25 19:43

from django.db import migrations, models
import facetest.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FaceTestModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="테스트 이름")),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                (
                    "model_file",
                    models.FileField(
                        upload_to=facetest.models.file_upload_path,
                        verbose_name="모델 파일(.pth)",
                    ),
                ),
                (
                    "result_types_file",
                    models.FileField(
                        upload_to=facetest.models.file_upload_path,
                        verbose_name="결과 유형 파일(JSON)",
                    ),
                ),
                (
                    "train_script",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=facetest.models.file_upload_path,
                        verbose_name="학습 스크립트(train.py)",
                    ),
                ),
                (
                    "predict_script",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=facetest.models.file_upload_path,
                        verbose_name="예측 스크립트(predict.py)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성화")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
            ],
            options={
                "verbose_name": "얼굴상 테스트",
                "verbose_name_plural": "얼굴상 테스트",
            },
        ),
    ]
