# Generated by Django 4.2.20 on 2025-04-25 18:55

from django.db import migrations, models
import facetest.models


class Migration(migrations.Migration):

    dependencies = [
        ("facetest", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="facemodel",
            name="types_json",
            field=models.FileField(
                blank=True,
                help_text="얼굴 유형 정보가 포함된 JSON 파일",
                null=True,
                upload_to="face_models/",
                verbose_name="얼굴 유형 JSON",
            ),
        ),
        migrations.AlterField(
            model_name="facetype",
            name="image",
            field=models.ImageField(
                blank=True,
                upload_to=facetest.models.face_type_image_upload_path,
                verbose_name="대표 이미지",
            ),
        ),
    ]
