# Generated by Django 4.2.20 on 2025-04-25 21:39

from django.db import migrations, models
import facetest.models


class Migration(migrations.Migration):

    dependencies = [
        ("facetest", "0002_faceresulttype_faceresultimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="facetestmodel",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="권장 크기: 140x160px, 테스트 목록에 표시됩니다.",
                null=True,
                upload_to=facetest.models.test_image_upload_path,
                verbose_name="대표 이미지",
            ),
        ),
    ]
