# Generated by Django 4.2.20 on 2025-04-25 22:11

from django.db import migrations, models
import facetest.models


class Migration(migrations.Migration):

    dependencies = [
        ("facetest", "0004_facetestmodel_intro_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="facetestmodel",
            name="guide_image",
            field=models.ImageField(
                blank=True,
                help_text="권장 크기: 500x300px, 얼굴 업로드 가이드로 표시됩니다.",
                null=True,
                upload_to=facetest.models.test_image_upload_path,
                verbose_name="업로드 가이드 이미지",
            ),
        ),
        migrations.AddField(
            model_name="facetestmodel",
            name="upload_guide",
            field=models.TextField(
                blank=True,
                help_text="얼굴 이미지 업로드시 표시할 가이드 텍스트입니다.",
                verbose_name="업로드 가이드",
            ),
        ),
    ]
