# Generated by Django 4.2.20 on 2025-04-26 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facetest", "0005_facetestmodel_guide_image_facetestmodel_upload_guide"),
    ]

    operations = [
        migrations.AddField(
            model_name="facetestmodel",
            name="view_count",
            field=models.PositiveIntegerField(default=0, verbose_name="조회수"),
        ),
    ]
