# Generated by Django 4.2.20 on 2025-04-26 14:34

from django.db import migrations, models
import facetest.models


class Migration(migrations.Migration):

    dependencies = [
        ("facetest", "0006_facetestmodel_view_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="faceresulttype",
            name="background_color",
            field=models.CharField(
                default="#FFF5EE",
                help_text="예: #FFFFFF, rgb(255,255,255), mintcream 등",
                max_length=20,
                verbose_name="배경색",
            ),
        ),
        migrations.AddField(
            model_name="faceresulttype",
            name="sub_image",
            field=models.ImageField(
                blank=True,
                help_text="권장 크기: 500x300px, 결과 설명 대신 표시됩니다.",
                null=True,
                upload_to=facetest.models.result_image_upload_path,
                verbose_name="결과 보조 이미지",
            ),
        ),
    ]
