# Generated by Django 4.2.20 on 2025-04-27 19:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("facetest", "0007_faceresulttype_background_color_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FaceTestResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="고유 ID",
                    ),
                ),
                (
                    "image_path",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="이미지 경로",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "face_test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="facetest.facetestmodel",
                        verbose_name="테스트",
                    ),
                ),
                (
                    "result_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_results",
                        to="facetest.faceresulttype",
                        verbose_name="결과 유형",
                    ),
                ),
            ],
            options={
                "verbose_name": "얼굴상 테스트 결과",
                "verbose_name_plural": "얼굴상 테스트 결과",
                "ordering": ["-created_at"],
            },
        ),
    ]
