# Generated by Django 4.2.20 on 2025-04-23 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BoardCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="카테고리명")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True, unique=True, verbose_name="슬러그"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="순서")),
                ("is_active", models.BooleanField(default=True, verbose_name="활성화")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
            ],
            options={
                "verbose_name": "게시판 카테고리",
                "verbose_name_plural": "게시판 카테고리",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                ("content", models.TextField(verbose_name="내용")),
                (
                    "view_count",
                    models.PositiveIntegerField(default=0, verbose_name="조회수"),
                ),
                (
                    "is_notice",
                    models.BooleanField(default=False, verbose_name="공지사항"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="작성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="작성자",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="community.boardcategory",
                        verbose_name="카테고리",
                    ),
                ),
            ],
            options={
                "verbose_name": "게시글",
                "verbose_name_plural": "게시글",
                "ordering": ["-is_notice", "-created_at"],
            },
        ),
    ]
