# Generated by Django 4.2.20 on 2025-04-28 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0003_post_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="like_count",
            field=models.PositiveIntegerField(default=0, verbose_name="좋아요 수"),
        ),
    ]
