# Generated by Django 4.2.11 on 2025-11-11 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sources", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CrawlLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "성공"),
                            ("failed", "실패"),
                            ("partial", "부분 성공"),
                        ],
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "items_collected",
                    models.IntegerField(default=0, verbose_name="수집 건수"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="에러 메시지"),
                ),
                ("started_at", models.DateTimeField(verbose_name="시작 시간")),
                ("completed_at", models.DateTimeField(verbose_name="완료 시간")),
                ("duration_seconds", models.FloatField(verbose_name="소요 시간(초)")),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crawl_logs",
                        to="sources.datasource",
                        verbose_name="데이터 소스",
                    ),
                ),
            ],
            options={
                "verbose_name": "크롤링 로그",
                "verbose_name_plural": "크롤링 로그 목록",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="CollectedData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        help_text="각 타입마다 다른 구조를 가질 수 있음",
                        verbose_name="수집된 데이터",
                    ),
                ),
                (
                    "hash_key",
                    models.CharField(
                        help_text="중복 데이터 방지를 위한 해시값",
                        max_length=64,
                        unique=True,
                        verbose_name="해시 키",
                    ),
                ),
                (
                    "collected_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="수집일시"),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collected_data",
                        to="sources.datasource",
                        verbose_name="데이터 소스",
                    ),
                ),
            ],
            options={
                "verbose_name": "수집 데이터",
                "verbose_name_plural": "수집 데이터 목록",
                "ordering": ["-collected_at"],
                "indexes": [
                    models.Index(
                        fields=["-collected_at"], name="collector_c_collect_b50e21_idx"
                    ),
                    models.Index(
                        fields=["source", "-collected_at"],
                        name="collector_c_source__d8fd5d_idx",
                    ),
                ],
            },
        ),
    ]
