# Generated by Django 4.2.20 on 2025-04-30 23:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("misc", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FortuneCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="카테고리명")),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="순서")),
                ("is_active", models.BooleanField(default=True, verbose_name="활성화")),
            ],
            options={
                "verbose_name": "운세 카테고리",
                "verbose_name_plural": "운세 카테고리 관리",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="FortuneType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="유형명")),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL에 사용될 이름",
                        unique=True,
                        verbose_name="슬러그",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="misc/fortune/types/",
                        verbose_name="이미지",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="순서")),
                ("is_active", models.BooleanField(default=True, verbose_name="활성화")),
                (
                    "is_ready",
                    models.BooleanField(default=False, verbose_name="서비스 준비됨"),
                ),
            ],
            options={
                "verbose_name": "운세 유형",
                "verbose_name_plural": "운세 유형 관리",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="UserFortune",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="세션 ID"
                    ),
                ),
                ("date", models.DateField(verbose_name="날짜")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "fortune_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="misc.fortunetype",
                        verbose_name="운세 유형",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "사용자 운세 결과",
                "verbose_name_plural": "사용자 운세 결과 관리",
                "unique_together": {
                    ("user", "fortune_type", "date"),
                    ("session_id", "fortune_type", "date"),
                },
            },
        ),
        migrations.CreateModel(
            name="FortuneContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.IntegerField(
                        default=3,
                        help_text="1(매우 나쁨) ~ 5(매우 좋음)",
                        verbose_name="운세 등급",
                    ),
                ),
                ("content", models.TextField(verbose_name="내용")),
                ("advice", models.TextField(blank=True, verbose_name="조언")),
                ("is_active", models.BooleanField(default=True, verbose_name="활성화")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contents",
                        to="misc.fortunecategory",
                        verbose_name="카테고리",
                    ),
                ),
                (
                    "fortune_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contents",
                        to="misc.fortunetype",
                        verbose_name="운세 유형",
                    ),
                ),
            ],
            options={
                "verbose_name": "운세 내용",
                "verbose_name_plural": "운세 내용 관리",
            },
        ),
        migrations.CreateModel(
            name="UserFortuneResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="misc.fortunecategory",
                        verbose_name="카테고리",
                    ),
                ),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="misc.fortunecontent",
                        verbose_name="운세 내용",
                    ),
                ),
                (
                    "user_fortune",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="misc.userfortune",
                        verbose_name="사용자 운세",
                    ),
                ),
            ],
            options={
                "verbose_name": "사용자 운세 세부 결과",
                "verbose_name_plural": "사용자 운세 세부 결과 관리",
                "unique_together": {("user_fortune", "category")},
            },
        ),
    ]
