# Generated by Django 4.2.11 on 2026-07-24 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moscom', '0005_region_overview_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_uuid', models.CharField(db_index=True, max_length=64, verbose_name='장비 UUID')),
                ('device_name', models.CharField(blank=True, default='', max_length=120, verbose_name='관측소명')),
                ('region_name', models.CharField(blank=True, default='', max_length=80, verbose_name='권역')),
                ('snapshot_date', models.DateField(db_index=True, verbose_name='예측 산출일')),
                ('target_date', models.DateField(db_index=True, verbose_name='예측 대상일')),
                ('horizon_days', models.IntegerField(default=0, verbose_name='예측 시평(일)')),
                ('predicted', models.IntegerField(default=0, verbose_name='예측 마릿수(방역 반영)')),
                ('predicted_raw', models.IntegerField(default=0, verbose_name='예측 마릿수(방역 미반영)')),
                ('predicted_index', models.FloatField(blank=True, null=True, verbose_name='예측 모기지수')),
                ('grade', models.CharField(blank=True, default='', max_length=10, verbose_name='예측 등급')),
                ('remedy_factor', models.FloatField(default=1.0, verbose_name='방역 계수')),
                ('lag1', models.IntegerField(default=0, verbose_name='전일 실측')),
                ('lag7', models.IntegerField(default=0, verbose_name='7일전 실측')),
                ('ma3', models.FloatField(default=0, verbose_name='3일 이동평균')),
                ('ma7', models.FloatField(default=0, verbose_name='7일 이동평균')),
                ('temperature', models.FloatField(blank=True, null=True, verbose_name='기온')),
                ('humidity', models.FloatField(blank=True, null=True, verbose_name='습도')),
                ('precipitation', models.FloatField(blank=True, null=True, verbose_name='강수')),
                ('wind_speed', models.FloatField(blank=True, null=True, verbose_name='풍속')),
                ('actual', models.IntegerField(blank=True, null=True, verbose_name='실측 마릿수')),
                ('error', models.IntegerField(blank=True, null=True, verbose_name='오차(실측-예측)')),
                ('abs_error_pct', models.FloatField(blank=True, null=True, verbose_name='절대 오차율(%)')),
                ('matched_at', models.DateTimeField(blank=True, null=True, verbose_name='실측 대조 시각')),
                ('model_version', models.CharField(blank=True, default='', max_length=20, verbose_name='모델 버전')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='생성 시각')),
            ],
            options={
                'verbose_name': 'AI 예측 로그',
                'verbose_name_plural': 'AI 예측 로그',
                'ordering': ['-target_date', '-snapshot_date'],
            },
        ),
        migrations.RenameIndex(
            model_name='collection',
            new_name='moscom_coll_device__6d19f0_idx',
            old_name='moscom_coll_device__cd6e6f_idx',
        ),
        migrations.RenameIndex(
            model_name='collection',
            new_name='moscom_coll_created_004ca8_idx',
            old_name='moscom_coll_created_idx',
        ),
        migrations.AddIndex(
            model_name='predictionlog',
            index=models.Index(fields=['device_uuid', '-target_date'], name='moscom_pred_device__0e20ef_idx'),
        ),
        migrations.AddIndex(
            model_name='predictionlog',
            index=models.Index(fields=['-snapshot_date'], name='moscom_pred_snapsho_e18d7b_idx'),
        ),
        migrations.AddIndex(
            model_name='predictionlog',
            index=models.Index(fields=['target_date', 'actual'], name='moscom_pred_target__c3f8e3_idx'),
        ),
        migrations.AddConstraint(
            model_name='predictionlog',
            constraint=models.UniqueConstraint(fields=('device_uuid', 'snapshot_date', 'target_date'), name='uniq_prediction_snapshot'),
        ),
    ]
