# Generated by Django 4.2.11 on 2025-11-11 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="예: 리그오브레전드 공지사항",
                        max_length=200,
                        verbose_name="데이터 소스명",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=200, unique=True, verbose_name="슬러그"
                    ),
                ),
                ("url", models.URLField(max_length=500, verbose_name="크롤링 URL")),
                (
                    "crawler_type",
                    models.CharField(
                        choices=[
                            ("beautifulsoup", "BeautifulSoup"),
                            ("selenium", "Selenium"),
                            ("api", "API"),
                            ("rss", "RSS"),
                        ],
                        default="beautifulsoup",
                        max_length=20,
                        verbose_name="크롤러 타입",
                    ),
                ),
                (
                    "crawler_class",
                    models.CharField(
                        blank=True,
                        help_text="예: collector.crawlers.game_crawlers.LOLNoticeCrawler",
                        max_length=200,
                        verbose_name="크롤러 클래스명",
                    ),
                ),
                (
                    "crawl_interval",
                    models.IntegerField(
                        default=10,
                        help_text="몇 분마다 크롤링할지 설정",
                        verbose_name="크롤링 주기(분)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성화")),
                (
                    "last_crawled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="마지막 크롤링 시간"
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="크롤러별 추가 설정을 JSON 형식으로 저장",
                        verbose_name="크롤러 설정",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "subcategory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_sources",
                        to="core.subcategory",
                        verbose_name="하위 카테고리",
                    ),
                ),
            ],
            options={
                "verbose_name": "데이터 소스",
                "verbose_name_plural": "데이터 소스 목록",
                "ordering": ["-created_at"],
            },
        ),
    ]
