# Generated by Django 4.2.11 on 2025-11-12 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sources", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datasource",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="비워두면 자동으로 생성됩니다",
                max_length=200,
                unique=True,
                verbose_name="슬러그",
            ),
        ),
    ]
